### ISSUE TITLE
Customizing the exportFromJSON delimiter

### ISSUE THREAD

**Issue by riohdan** [tuanzisama/elTableExport#2]
Hi,

Can you add the option/props to customize the exportFromJSON delimiter ?

Thanks! 

<img width="667" alt="Capture d’écran, le 2020-08-20 à 07 37 39" src="https://user-images.githubusercontent.com/5587632/90765508-1016a200-e2b8-11ea-9b04-baf5a9f5a331.png">

**Comment by tuanzisama** [comment]
Thank you for your pull request, it has now been merged.
