### ISSUE TITLE
分页打印不了

### ISSUE THREAD

**Issue by landaozhu** [tuanzisama/elTableExport#4]
分页

**Comment by tuanzisama** [comment]
嗨！分页组件`el-pagination` 无法存在于Excel中，并且不符合 `el-table` 导出逻辑，如果有异议，请详细提出。
Hi! The component `el-pagination` cannot exist in Excel and does not conform to the export logic of `el-table`.
If there is any objection, please raise it in detail.

**Comment by landaozhu** [comment]
不是说excel要分页 而是应该支持打印所有数据 不可能只打印当前页的数据 
已提交pr 请看pr 我自己暂时公司用的是我改造后发的包 等你更新后再用你的

**Comment by tuanzisama** [comment]
看到PR之后我明白了你的意思，但这并不符合此项目。
推荐使用 [export-from-json](https://www.npmjs.com/package/export-from-json)

After seeing the Pull Request, I understand what you mean, but this is not in line with this project.
Recommend to use [export-from-json](https://www.npmjs.com/package/export-from-json)

**Comment by landaozhu** [comment]
你说的那个项目不是el table的吧 我在你的基础上加个导出全部没啥问题吧
