### ISSUE TITLE
can't recognize prop with "."

### ISSUE THREAD

**Issue by yexing** [tuanzisama/elTableExport#6]
ref.columns.forEach(element => {
            if(element.property) {
                let props = element.property.split(".");
                let v = cur;
                for(let prop of props) {
                    v = v[prop]
                }

                let val = v;
    
                if (val && element.formatter && __options.useFormatter)
                    val = element.formatter(cur, element);
                obj[element.label] = val || '';
            }
        });

**Comment by tuanzisama** [comment]
你可以描述如何出现这个问题的吗？
如果你认为此处有bug，可发起Pull Request。:)

Well, can you describe how this problem occurred? 
If you think there is a bug here, you can initiate a Pull Request. :)
